name = "konma-org/karbonledger"
version = "0.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'konma-org/karbonledger'"

[repository]
user = "konma-org"
project = "karbonledger"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "logical-mechanism/assist"
version = "v0.5.1"
source = "github"

[[dependencies]]
name = "cardano-fans/acca"
version = "a3a886b1e3557d00ed491a73001020a533cf34cd"
source = "github"

[config]
